const dialogs = Object.freeze({
  DIALOGS_SET_ITEMS: 'DIALOGS_SET_ITEMS',
  DIALOGS_FETCH_ITEMS: 'DIALOGS_FETCH_ITEMS',
  DIALOGS_START_FETCHING: 'DIALOGS_START_FETCHING',
  DIALOGS_STOP_FETCHING: 'DIALOGS_STOP_FETCHING',
  DIALOGS_FETCHING_ERROR: 'DIALOGS_FETCHING_ERROR',

  DIALOGS_SET_CURRENT_DIALOG_ID: 'DIALOGS_SET_CURRENT_DIALOG_ID',
});

export default dialogs;
